// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDve4boP_1hdy8dBA9WEDfcTNTt6zBZMis',
    appId: '1:22193740927:web:055e6e1bb795a4afd1b34a',
    messagingSenderId: '22193740927',
    projectId: 'nynorsk-kartlegger',
    authDomain: 'nynorsk-kartlegger.firebaseapp.com',
    storageBucket: 'nynorsk-kartlegger.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYHbwXKa2uADXNwkI4kByaHkkmqvcTCbc',
    appId: '1:22193740927:android:59d13d30921f9de7d1b34a',
    messagingSenderId: '22193740927',
    projectId: 'nynorsk-kartlegger',
    storageBucket: 'nynorsk-kartlegger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsbXcEnPOMeyfJoDK6D7xT10jXqyKrZAs',
    appId: '1:22193740927:ios:677d2642917c0f7bd1b34a',
    messagingSenderId: '22193740927',
    projectId: 'nynorsk-kartlegger',
    storageBucket: 'nynorsk-kartlegger.firebasestorage.app',
    iosBundleId: 'com.nynorsk.nynorskKartlegger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsbXcEnPOMeyfJoDK6D7xT10jXqyKrZAs',
    appId: '1:22193740927:ios:677d2642917c0f7bd1b34a',
    messagingSenderId: '22193740927',
    projectId: 'nynorsk-kartlegger',
    storageBucket: 'nynorsk-kartlegger.firebasestorage.app',
    iosBundleId: 'com.nynorsk.nynorskKartlegger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDve4boP_1hdy8dBA9WEDfcTNTt6zBZMis',
    appId: '1:22193740927:web:90e92171c6a2d30bd1b34a',
    messagingSenderId: '22193740927',
    projectId: 'nynorsk-kartlegger',
    authDomain: 'nynorsk-kartlegger.firebaseapp.com',
    storageBucket: 'nynorsk-kartlegger.firebasestorage.app',
  );
}
